MUSICPLAYER/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from player import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('player.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

player/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('sign_up/', views.signup, name='signup'),
    path('sign_in/', views.signin, name='signin'),
    path('logout/', views.signout, name='logout'),
    path('library/', views.playlists, name='library'),
    path('playlist/<int:playlist_id>', views.showplaylist, name='showplaylist'),
    path('upload_song/', views.uploadsong, name='uploadsong'),
    path('upload_album/', views.uploadalbum, name='uploadalbum'),
    path('album/<int:album_id>', views.album, name='album'),
    path('album/<int:album_id>/like', views.likeAlbum, name='like'),
    path('album/<int:album_id>/unlike', views.unlikeAlbum, name='unlike'),
    path('songs/<int:song_id>', views.songView, name='song'),
    path('songs/<int:song_id>/like/', views.likeSong, name='likeSong'),
    path('songs/<int:song_id>/unlike/', views.unlikeSong, name='unlikeSong'),
    path('saved/', views.library, name='saved'),
    path('create_playlist/', views.createplaylist, name='createplaylist'),
    path('playlist/<int:playlist_id>/update/', views.update_playlist, name='update_playlist'),
    path('artist/<int:artist_id>/', views.artist_detail, name='artist'),
    path('artist/<int:artist_id>/unfollow', views.unfollow_artist, name='unfollow'),
    path('artist/<int:artist_id>/follow', views.follow_artist, name='follow'),
    path('artist/<int:artist_id>/songs', views.artist_songs, name='artist_songs'),
    path('results/', views.search, name='results'),
    path('profile/<int:profile_id>/following/', views.followingView, name='following'),
    path('playlist/<int:playlist_id>/delete', views.deleteplaylist, name='deleteplaylist'),
    path('profile/<int:user_id>/', views.profile, name='profile'),  # Muestra el perfil basado en el user_id
    path('profile/<int:profile_id>/update/', views.update_profile, name='updateprofile'),  # Actualiza el perfil basado en el profile_id
]

player/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.   

class Artist(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField(blank=True)
    pic = models.ImageField(upload_to='artist_pic/', blank=True, null=True)
    followers = models.ManyToManyField(User, related_name='followers', blank=True)
    
    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=100)
    dateofrelease = models.CharField(max_length=30)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, null=True)
    cover = models.ImageField(upload_to='album_photo/', blank=True, null=True)
    
    def __str__(self):
        return f"{self.title}"
    

class Song(models.Model):
    title = models.CharField(max_length=100)
    album = models.ForeignKey(Album, on_delete=models.CASCADE ,blank=True)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='songs')
    audio_file = models.FileField(upload_to='audio/', blank=True, null=True)
    songcover = models.ImageField(upload_to='song_photo/', blank=True, null=True)
            
    def __str__(self):
        return self.title
    def total_likes(self):
        return self.liked_by.count()

class Profile(models.Model):
    nickname = models.CharField(max_length=50, blank=True, null=True)
    pfp = models.ImageField(upload_to='profile_pics/', default='default_pfp.jpg')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers = models.ManyToManyField(User, related_name='user_followers', blank=True)
    following = models.ManyToManyField('self', symmetrical=False, related_name='user_following', blank=True)
    #el symmetrical=False dice que la relacion no necesariamente es simetrica, que si el user 1 sigue al 2, 
    #no significa que el 2 siga al 1
    followed_artists = models.ManyToManyField(Artist, related_name='followed_artists', blank=True)
    liked_albums = models.ManyToManyField(Album, related_name='liked_albums', blank=True)
    liked_songs = models.ManyToManyField(Song, related_name='liked_songs', blank=True)
    
    def __str__(self):
        return f"{self.user}"  

class Playlist(models.Model):
    title = models.CharField(max_length=100,blank=True)
    description = models.TextField(blank=True)
    artists = models.ManyToManyField(Artist, related_name='playlists')
    songs = models.ManyToManyField(Song, related_name='playlists', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    datecreated = models.DateField(null=True)
    photo = models.ImageField(upload_to='playlist_photo/', default='default-cover.png', blank=True, null=True)
    public = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.title} - {self.user}"

player/forms.py
from django import forms
from .models import Song, Album, Playlist, Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['title', 'artist', 'album', 'audio_file']
        
class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'artist', 'cover', 'dateofrelease']
        
class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['title', 'description', 'photo', 'songs', 'public']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-title', 'placeholder': 'ENTER TITLE'}),
            'description': forms.TextInput(attrs={'class': 'form-description', 'placeholder': 'ENTER DESCRIPTION'}),
            'photo': forms.FileInput(attrs={'class': 'form-photo', 'placeholder': 'upload photo'}),
            'public': forms.CheckboxInput(attrs={'class': 'form-public', 'placeholder': 'public'}),
            'songs': forms.SelectMultiple(attrs={'class': 'form-songs', 'placeholder': 'choose songs'}),
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'pfp']

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')  
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-username', 'placeholder': 'Username'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-password1', 'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-password2', 'placeholder': 'Confirm Password'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'usable_password' in self.fields:
            del self.fields['usable_password']

player/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .forms import SongForm, AlbumForm, PlaylistForm, ProfileForm, CustomUserCreationForm
from .models import Playlist, Song, Album, Artist, Profile
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages
from django.db.models import Q, Count
from thefuzz import process

def index(request):
    artist = Artist.objects.all()
    rec_albums = Album.objects.order_by('?')[:3]
        
    #checkeo si esta loggeado el usuario   
    if request.user.is_authenticated:
        #si lo esta va a agarrar el objeto aleatorio de la tabla playlist
        rec_playlist = Playlist.objects.filter(user=request.user).order_by('?').first()
        rec_albums = rec_albums[:2]
    else:
        #se pone el none para que no tire error, ya q en el inicio yo puse para que se muestren recomendaciones
        #del user q esta logeado
        rec_playlist = None
        rec_albums = rec_albums[:3]
    rec_artist = Artist.objects.order_by('?').first()
    profile = Profile.objects.all()
    return render(request, 'layout/home.html', {
        'profile': profile,
        'rec_artist': rec_artist,
        'rec_albums': rec_albums,
        'rec_playlist': rec_playlist,
        'artist': artist
    })

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'invalid data')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/signup.html', {
        'form': form,
    })

def signin(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'invalid username or password')
    else:
        form = AuthenticationForm()
    return render(request, 'users/signin.html', {
        'form': form
    })

def signout(request):
    logout(request)
    return redirect('signin')

@login_required
def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    profile, created = Profile.objects.get_or_create(user=user)
    playlist = Playlist.objects.filter(user=user)
    is_owner = request.user == user

    if created:
        profile.nickname = user.username
        profile.pfp = 'default_pfp.jpg'
        profile.save()
    else:
        return render(request, 'users/profile.html', {
            'playlist': playlist,
            'profile': profile,
            'is_owner': is_owner
        })

   
@login_required
def update_profile(request, profile_id):
    profile = get_object_or_404(Profile, pk=profile_id)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile', user_id=profile.user.id)
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'users/update_profile.html', {
        'profile': profile,
        'form': form
    })

def search(request):
    query = request.POST.get('q')
    songs = Song.objects.all()
    albums = Album.objects.all()
    artists = Artist.objects.all()
    
    if query:
        song_titles = [song.title for song in songs]
        artist_names = [artist.name for artist in artists]
        album_titles = [album.title for album in albums]
        
        song_matches = process.extract(query, song_titles, limit=len(song_titles))
        matched_song_titles = [match[0] for match in song_matches if match[1] > 70]
        
        artist_matches = process.extract(query, artist_names, limit=len(artist_names))
        matched_artist_names = [match[0] for match in artist_matches if match[1] > 70]
        
        album_matches = process.extract(query,album_titles, limit=len(album_titles))
        matched_album_titles = [match[0] for match in album_matches if match[1] > 70]
        
        songs = songs.filter(Q(title__in=matched_song_titles)|Q(artist__name__in=matched_artist_names))
        artists = artists.filter(Q(name__in=matched_artist_names))
        albums = albums.filter(Q(title__in=matched_album_titles)|Q(artist__name__in=matched_artist_names))
        
        
    return render(request, 'search/results.html', {
        'songs': songs,
        'artists': artists,
        'albums': albums,
    })
    
def artist_songs(request, artist_id):
    artist = Artist.objects.get(id=artist_id)
    songs = Song.objects.filter(artist=artist)
    return render(request, 'artist/songs.html', {
        'songs': songs,
        'artist': artist,
    })
    
@login_required
def playlists(request):
    user = request.user
    albums = Album.objects.all()
    user_playlists = Playlist.objects.filter(user=request.user)
    return render(request, 'songs/playlists_display.html', {
        'playlist': user_playlists,
        'albums': albums,
        'user': user
    })
    
def showplaylist(request, playlist_id):
    playlist = get_object_or_404(Playlist, pk=playlist_id)
    songs =  playlist.songs.all()
    artist = songs.first().artist if songs.exists() and songs.first().artist else None
    return render(request, 'songs/show_playlist.html', {
        'playlist': playlist,
        'songs': songs,
        'artist': artist,
    })

@login_required
def update_playlist(request, playlist_id):
        
    playlist = get_object_or_404(Playlist, pk=playlist_id)
    if request.method == 'POST':
        form = PlaylistForm(request.POST, request.FILES, instance=playlist)
        if form.is_valid():
            form.save()
            return redirect('showplaylist', playlist_id=playlist.id)
    else:
        form = PlaylistForm(instance=playlist)

    return render(request, 'songs/update_playlist.html', {'form': form, 'playlist': playlist})

@login_required
def deleteplaylist(request, playlist_id):
    playlist = get_object_or_404(Playlist, pk=playlist_id, user=request.user)
    if request.method == 'POST':
        messages.success(request, 'Playlist deleted successfully')
        playlist.delete()
        return redirect('library')
    
    return render(request, 'songs/confirm_delete.html', {'playlist': playlist})

def album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    user = request.user
    
    if user.is_authenticated:
        liked_albums = request.user.profile.liked_albums.all()
        return render(request, 'artist/album.html', {
            'album': album,
            'liked_albums': liked_albums
        })
    else:
        return render(request, 'artist/album.html', {
            'album': album,
        })



def songView(request, song_id):
    songs = get_object_or_404(Song, pk=song_id)
    user = request.user
    
    if user.is_authenticated:
        liked_songs = request.user.profile.liked_songs.all()
        return render(request, 'songs/song.html', {
            'songs': songs,
            'liked_songs': liked_songs
        })
    else:
        return render(request, 'songs/song.html', {
            'songs': songs
        })

def uploadsong(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden('You are not allowed to access this page')

    if request.method == 'POST':
        form = SongForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('songlist')
    else:
        form = SongForm()

    return render(request, 'songs/upload_song.html', {
        'form': form
    })
            
def uploadalbum(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden("You are not allowed to access this page.")
    
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('songs/album_list')
    else:
        form = AlbumForm()
    return render(request, 'create_album.html', {'form': form})

def createplaylist(request):
    if request.method == 'POST':
        form = PlaylistForm(request.POST, request.FILES)
        if form.is_valid():
            playlist = form.save(commit=False)
            playlist.user = request.user
            playlist.save()
            return redirect('library')
    else:
        form = PlaylistForm()
    return render(request, 'songs/create_playlist.html', {
        'form': form
    })

def artist_detail(request, artist_id):    
    artist = get_object_or_404(Artist, id=artist_id)
    album = Album.objects.filter(artist=artist)
    songs = Song.objects.filter(artist=artist).annotate(total_likes=Count('liked_songs')).order_by('-total_likes')
    
    if request.user.is_authenticated:
        user = request.user
        is_following = artist.followers.filter(id=request.user.id).exists()
        liked_artists_count = Artist.objects.filter(followers=user).count()
        return render(request, 'artist/artist.html', {
            'songs': songs,
            'artist': artist,
            'is_following': is_following,
            'liked_artists_count': liked_artists_count,
            'album': album
        })
         
    else:
        return render(request, 'artist/artist.html', {
            'songs': songs,
            'artist': artist,
            'album': album
        })


    
    
def followingView(request, profile_id):
    profile = get_object_or_404(Profile, pk=profile_id)
    

player/templates/songs/create_album.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Create an Album</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
</body>
</html>

player/templates/songs/create_album.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Create an Album</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
</body>
</html>

player/templates/songs/create_playlist.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'stylesheets/create_playlist.css' %}">
</head>
<body>
    {% include 'layout/navbar.htm' %}
    <div class="form-container">
        <div class="form">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>create playlist</h3>
                <div class="image-upload">
                    <label for="id_photo">
                        <img id="preview" src="/media/default-cover.png" alt="Default Cover" class="upload-preview">
                    </label>
                    {{ form.photo }}
                </div>
                <div class="info">
                    {{ form.title }}
                    {{ form.description }}
                    {{ form.photo }}
                    {{form.songs}}
                    <p>make public {{ form.public }}</p>
                    <button class="create">create</button>
                </div>                
            </form>
    </div>
</body>
</html>
<script>
    document.getElementById('id_photo').addEventListener('change', function(event) {
        const file = event.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function(e) {
                document.getElementById('preview').src = e.target.result;
            }
            reader.readAsDataURL(file);
        }
    });
</script>

player/templates/songs/create_playlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'stylesheets/create_playlist.css' %}">
</head>
<body>
    {% include 'layout/navbar.html' %}
    <div class="form-container">
        <div class="form">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>create playlist</h3>
                <div class="image-upload">
                    <label for="id_photo">
                        <img id="preview" src="/media/default-cover.png" alt="Default Cover" class="upload-preview">
                    </label>
                    {{ form.photo }}
                </div>
                <div class="info">
                    {{ form.title }}
                    {{ form.description }}
                    {{ form.photo }}
                    {{form.songs}}
                    <p>make public {{ form.public }}</p>
                    <button class="create">create</button>
                </div>                
            </form>
    </div>
</body>
</html>
<script>
    document.getElementById('id_photo').addEventListener('change', function(event) {
        const file = event.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function(e) {
                document.getElementById('preview').src = e.target.result;
            }
            reader.readAsDataURL(file);
        }
    });
</script>

player/templates/songs/library.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'stylesheets/library.css' %}">
</head>
<body>
    {% include 'layout/navbar.htm' %}
    {% block content %}
    <div class="display">
            <div class="separation">
                <img id="preview" src="/media/default-cover.png" alt="Default Cover" class="upload-preview">
                <p>Liked Songs</p>
            </div>
    </div>
    <div class="div-songs">
        <div class="songs">
            {% if liked_songs %}
                {% for song in liked_songs %}
            <div class="cards">
                <div class="song-details" onclick="togglePlayPause(this)"> <!-- Nuevo contenedor -->
                    <div class="cover">
                        {% if song.songcover %}
                        <img id="portada" loading="lazy" src="{{ song.songcover.url }}" alt="">
                        {% endif %}
                    </div>
                    <div class="rest">
                        <p>{{ song.title }}</p>
                        {% if song.artist %}
                        <a href="{% url 'artist' song.artist.id %}">{{song.artist}}</a>
                        {% endif %}
                    </div>
                    <div class="play-button">
                        {% if song.audio_file %}
                        <div class="audio-div">
                            <audio id="audioPlayer" src="{{ song.audio_file.url }}" type="audio/mpeg"></audio>
                            <button id="playPauseBtn" class="play-btn">
                                <img id="playIcon" src="{% static 'img/play.png' %}" alt="Play" style="display: block;">
                                <p style="display: none;">hola</p>
                                <img id="pauseIcon" src="{% static 'img/pause.png' %}" alt="Pause" style="display: none;">
                            </button>
                        </div>
                        {% endif %}
                    </div>
                </div> <!-- Fin del nuevo contenedor -->
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}
<script>
    var audioPlayers = document.querySelectorAll('audio[id^="audioPlayer"]');
    var currentAudio = null;
    var currentlyPlayingDiv = null; // Variable para rastrear el div actualmente en reproducción
    
    // Mueve la función togglePlayPause fuera del DOMContentLoaded para hacerla accesible globalmente
    window.togglePlayPause = function(songDetailElement) {
        var audioPlayer = songDetailElement.querySelector('audio');
        var playIcon = songDetailElement.querySelector('#playIcon');
        var pauseIcon = songDetailElement.querySelector('#pauseIcon');
        var songDetailsDiv = songDetailElement.closest('.song-details');
    
        // Si se está reproduciendo otro audio, pausar el audio actual y restablecer el botón
        if (currentAudio && currentAudio !== audioPlayer) {
            currentAudio.pause();
            resetPlayPauseButton(currentlyPlayingDiv);
            currentlyPlayingDiv.classList.remove('playing');
        }
    
        // Reproducir o pausar el audio seleccionado
        if (audioPlayer.paused) {
            audioPlayer.volume = 0.2;
            audioPlayer.play();
            playIcon.style.display = 'none';
            pauseIcon.style.display = 'block';
            currentAudio = audioPlayer;
            currentlyPlayingDiv = songDetailsDiv;
    
            // Añade la clase .playing al contenedor del div
            songDetailsDiv.classList.add('playing');
        } else {
            audioPlayer.pause();
            playIcon.style.display = 'block';
            pauseIcon.style.display = 'none';
            currentAudio = null;
            currentlyPlayingDiv = null;
    
            // Remueve la clase .playing del contenedor del div
            songDetailsDiv.classList.remove('playing');
        }
    };
    
    // Evento para manejar el final de la canción
    audioPlayers.forEach(function(audioPlayer) {
        audioPlayer.addEventListener('ended', function() {
            resetPlayPauseButton(currentlyPlayingDiv);
            currentlyPlayingDiv.classList.remove('playing');
            currentAudio = null;
            currentlyPlayingDiv = null;
        });
    });
    
    // Función para restablecer el botón de reproducción/pausa
    function resetPlayPauseButton(songDetailElement) {
        if (!songDetailElement) return; // Asegúrate de que el elemento exista
        var playIcon = songDetailElement.querySelector('#playIcon');
        var pauseIcon = songDetailElement.querySelector('#pauseIcon');
        playIcon.style.display = 'block';
        pauseIcon.style.display = 'none';
    }
    
</script>

player/templates/songs/songs.htm
<!-- templates/includes/song_list.html -->
<div class="songs">
    {% for song in songs %}
        <p>{{ song.title }}</p>
        {% if song.audio_file %}
            <br>
            <audio controls>
                <source src="{{ song.audio_file.url }}" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
            <a href="{% url 'artist' song.artist.id %}">{{ song.artist.name }}</a>
        {% endif %}
    {% endfor %}
</div>

player/templates/songs/songs.html
<!-- templates/includes/song_list.html -->
<div class="songs">
    {% for song in songs %}
        <p>{{ song.title }}</p>
        {% if song.audio_file %}
            <br>
            <audio controls>
                <source src="{{ song.audio_file.url }}" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
            <a href="{% url 'artist' song.artist.id %}">{{ song.artist.name }}</a>
        {% endif %}
    {% endfor %}
</div>

player/templates/songs/update_playlist.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'stylesheets/create_playlist.css' %}">
</head>
<body>
    {% include 'layout/navbar.htm' %}
    <div class="form-container">
        <div class="form">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>edit info</h3>
                <div class="image-upload">
                    <label for="id_photo">
                        <img src="{% if playlist.photo %}{{ playlist.photo.url }}{% else %}path/to/default-image.png{% endif %}" alt="Click to upload" class="upload-preview">
                    </label>
                    {{ form.photo }} 
                </div>
                <div class="info">
                    {{ form.title }}
                    {{ form.description }}
                    {{form.songs}}
                    <p>make public {{ form.public }}</p>
                    <button type="submit" class="create">update</button>
                </div>
            </form>
            <button class="delete" type="submit">Eliminar</button>
            <div class="confirm">
                <h2>¿Estás seguro de que deseas eliminar la playlist "{{ playlist.title }}"?</h2>
                <p>Esta acción no se puede deshacer.</p>

                <form method="post" action="{% url 'deleteplaylist' playlist.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Sí, eliminar</button>
                    <a href="{% url 'update_playlist' playlist.id %}" class="btn btn-secondary">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    const form = document.querySelector('form');
    const confirm = document.querySelector('.confirm');
    const deleteBtn = document.querySelector('.delete');
    deleteBtn.addEventListener('click', () => {
        confirm.style.display = 'block';
        form.style.display = 'none';
    })
</script>

player/templates/songs/update_playlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'stylesheets/create_playlist.css' %}">
</head>
<body>
    {% include 'layout/navbar.html' %}
    <div class="form-container">
        <div class="form">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>edit info</h3>
                <div class="image-upload">
                    <label for="id_photo">
                        <img src="{% if playlist.photo %}{{ playlist.photo.url }}{% else %}path/to/default-image.png{% endif %}" alt="Click to upload" class="upload-preview">
                    </label>
                    {{ form.photo }} 
                </div>
                <div class="info">
                    {{ form.title }}
                    {{ form.description }}
                    {{form.songs}}
                    <p>make public {{ form.public }}</p>
                    <button type="submit" class="create">update</button>
                </div>
            </form>
            <button class="delete" type="submit">Eliminar</button>
            <div class="confirm">
                <h2>Are you sure you want to delete "{{ playlist.title }}"?</h2>
                <p>You can not undo this action</p>

                <form method="post" action="{% url 'deleteplaylist' playlist.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Yes, delete</button>
                    <a href="{% url 'update_playlist' playlist.id %}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    const form = document.querySelector('form');
    const confirm = document.querySelector('.confirm');
    const deleteBtn = document.querySelector('.delete');
    deleteBtn.addEventListener('click', () => {
        confirm.style.display = 'block';
        form.style.display = 'none';
    })
</script>